---
swagger: "2.0"
info: 
  version: "1.0.0"
  title: "Campaigns"

basePath: "/api"

tags:
- name: "campaigns"
  description: |
    The API for creating and maintaining campaigns.
schemes:
- http

securityDefinitions :
  ApiKeyAuth:
    type: apiKey
    in: header
    name: x-auth-token

paths:
  /campaign/heartbeat:
    get:
      tags:
      - campaigns
      operationId: heartbeat
      summary: "server heartbeat."
      description: "Simple health check."
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/heartbeat"
        500:
          description: "Unexpected Error"
          schema:
            $ref: "#/definitions/errors"
  
  /campaign:
    get:
      tags:
      - campaigns
      operationId: "search"
      summary: "Search campaigns based on campaign name"
      description: |
        Get a list of campaigns.
      parameters:
      - name: "x-auth-token"
        in: "header"
        description: "Access Token for calling the service"
        required: true
        type: "string"
      - name: "x-request-id"
        in: "header"
        description: "correlation id, if not provided will be generated by the api"
        required: false
        type: "string"
      - in: "query"
        name: "campaignName"
        description: "names to search for."
        type: "string"
        required: true
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/campaigns"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/errors"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/errors"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/errors"
        500:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/errors"
      security:
        - ApiKeyAuth: []

    post:
      tags:
      - campaigns
      operationId: "create"
      summary: "Create a new campaign."
      description: |
        Create a campaigns record.
      parameters:
      - name: "x-auth-token"
        in: "header"
        description: "Access Token for calling the service"
        required: true
        type: "string"
      - name: "x-request-id"
        in: "header"
        description: "correlation id, if not provided will be generated by the api"
        required: false
        type: "string"
      - in: "body"
        name: "body"
        description: "A JSON object instance."
        required: true
        schema:
          $ref: "#/definitions/campaignModel"
      responses:
        201:
          description: "Created"
          schema:
            $ref: "#/definitions/campaignResponseModel"         
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/errors"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/errors"
        500:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/errors"
      security:
        - ApiKeyAuth: []

  /campaign/{id}:
    get:
      tags:
      - campaigns
      operationId: "retrieve"
      summary: "Get an existing campaign."
      description: |
        Retrieve a campaign.
      parameters:
      - name: "x-auth-token"
        in: "header"
        description: "Access Token for calling the service"
        required: true
        type: "string"
      - name: "x-request-id"
        in: "header"
        description: "correlation id, if not provided will be generated by the api"
        required: false
        type: "string"
      - name: "id"
        in: "path"
        description: "The id of the campaign to retrieve."
        required: true
        type: "string"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/campaignResponseModel"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/errors"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/errors"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/errors"
        500:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/errors"
      security:
        - ApiKeyAuth: []

    put:
      tags:
      - campaigns
      operationId: "update"
      summary: "update an existing campaign record."
      description: |
        update an exiting campaign record.
      parameters:
      - name: "x-auth-token"
        in: "header"
        description: "Access Token for calling the service"
        required: true
        type: "string"
      - name: "x-request-id"
        in: "header"
        description: "correlation id, if not provided will be generated by the api"
        required: false
        type: "string"
      - name: "id"
        in: "path"
        description: "The id of the campaign to update."
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "A JSON object instance."
        required: true
        schema:
          $ref: "#/definitions/campaignModel"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/campaignResponseModel"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/errors"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/errors"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/errors"
        500:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/errors"
      security:
        - ApiKeyAuth: []

    delete:
      tags:
      - campaigns
      operationId: "delete"
      summary: "Delete an existing campaign record."
      description: "Delete campaign record by id."
      parameters:
      - name: "x-auth-token"
        in: "header"
        description: "Access Token for calling the service"
        required: true
        type: "string"
      - name: "x-request-id"
        in: "header"
        description: "correlation id, if not provided will be generated by the api"
        required: false
        type: "string"
      - name: "id"
        in: "path"
        description: "The id of the campaign to delete."
        required: true
        type: "string"
      responses:
        204:
          description: "OK"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/errors"
        403:
          description: "Forbidden"
          schema:
            $ref: "#/definitions/errors"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/errors"
        500:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/errors"
      security:
        - ApiKeyAuth: []     


definitions:
  errors:
    type: "object"
    description: "description of errors"
    properties:
      errors:
        type: "array"
        items:
          $ref: "#/definitions/error"
  
  error:
    type: "object"
  
  heartbeat:
    type: "object"
    description: "check server status"
    properties:
        message:
          type: "string"

  campaignResponseModel:
    allOf:
    - $ref: "#/definitions/campaignModel"
    - type: object
      properties:
        id:
          type: string
          description: Unique identifier
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

  campaigns:
    type: "array"
    items:
      $ref: "#/definitions/campaignResponseModel"

  campaignModel:
    type: "object"
    properties:
      campaignName:
        type: string
      description:
        type: string
      startDate:
        type: string
        format: date
      endDate:
        type: string
        format: date
    required:
    - campaignName
    - startDate
